default: &default
  url: '<%= ENV["DATABASE_URL"] %>'
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  username: portachat_api
  password: <%= ENV["PORTACHAT_API_DATABASE_PASSWORD"] %>
